### ISSUE TITLE
Y24-292 - [BUG] Exception 27/08/24 at 9:31

### ISSUE THREAD

**Issue by seenanair** [sanger/gatekeeper#437]
#### Email subject line

[Psd-exceptions] [Gatekeeper PRODUCTION] barcode_labels#create (NoMethodError) “undefined method `map’ for #<ActionController::Parameters...

#### Error body

```
A NoMethodError occurred in barcode_labels#create:

  undefined method `map' for #<ActionController::Parameters {"61854"=>"61854"} permitted: false>
  app/controllers/barcode_labels_controller.rb:30:in `generate_labels'
```

#### Acceptance Criteria

- [ ] Look into this exception and fix the code to handle the exception sensibly.
- [ ] Document the root cause and solution in a comment on this issue.

#### Additional information
The id of the user who triggered this error is often shown in the exception email, in case you need to communicate with them.

**Comment by stevieing** [comment]
A reoccurring exception is being thrown from Gatekeeper. (~52 occurrences since 2021)

e.g. 13/08/24

[Gatekeeper PRODUCTION] barcode_labels#create (NoMethodError) "undefined method `map' for #<ActionController::Parameters…

A NoMethodError occurred in barcode_labels#create:

e.g. undefined method map' for #<ActionController::Parameters {"61056"=>"61056"} permitted: false> app/controllers/barcode_labels_controller.rb:30:in generate_labels'

e.g. undefined method `map' for #<ActionController::Parameters {"44310"=>"44310", "44311"=>"44311", "44312"=>"44312", "44313"=>"44313", "44314"=>"44314", "44315"=>"44315"}

Look into what is causing this exception and discuss whether the fix is worthwhile with the team
